### PR TITLE
counter

### PR DESCRIPTION
**Pull request by Anna1-991**
Count letters, words and  sentences, also changes background color with random color with button 'change background'

### CODE REVIEW

**Comment by aramminas** [comment]
Hi Anna jan.
 I looked at your PR and found some issues, I only entered numbers and it gives me the result (no letters result) and also I noticed that you did not use all the methods mentioned in the requirements sections.
Please fix these issues.

**Comment by Anna1-991** [comment]
Thank you, I will do that.

**Comment by Anna1-991** [comment]
I have made some changes. thank you for reviewing my code.

**Comment by aramminas** [comment]
thank you for making these amendments.

**Review by aramminas — APPROVED** [review]

**Pull request merged**
